package com.nequi.inventory.infrastructure.persistence.dynamo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.nequi.inventory.domain.statemachine.TicketStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Ticket")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TicketEntity {

    @DynamoDBHashKey(attributeName = "eventId")
    private String eventId;

    @DynamoDBRangeKey(attributeName = "ticketId")
    private String ticketId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "status-index", attributeName = "status")
    @DynamoDBTypeConvertedEnum
    private TicketStatus status;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String orderId;

    @DynamoDBAttribute
    private String expiresAt;

    @DynamoDBVersionAttribute
    private Long version;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private String createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private String updatedAt;
}