version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: us-west-2

  redis:
    image: redis:7.2
    container_name: redis
    command: ["redis-server", "--requirepass", "SuperSecret123"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - LOCALSTACK_AUTH_TOKEN=ls-cUBI6223-vihE-3866-feTI-lOwuyEWIf5ed
    volumes:
      - ./localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws-queues-setup.sh:/etc/localstack/init/ready.d/aws-queues-setup.sh