spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: SuperSecret123
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms

  cloud:
    aws:
      region:
        static: us-west-2
      credentials:
        access-key: dummy
        secret-key: dummy

      sqs:
        endpoint: http://localhost:4566
        inventory-request-queue: http://sqs.us-west-2.localhost.localstack.cloud:4566/000000000000/inventory-request-queue.fifo
        inventory-response-queue: http://sqs.us-west-2.localhost.localstack.cloud:4566/000000000000/inventory-response-queue.fifo
        inventory-response-dlq: http://sqs.us-west-2.localhost.localstack.cloud:4566/000000000000/inventory-response-dlq.fifo
        order-ttl-queue: http://sqs.us-west-2.localhost.localstack.cloud:4566/000000000000/order-ttl-queue
        inventory-ttl-queue: http://sqs.us-west-2.localhost.localstack.cloud:4566/000000000000/inventory-ttl-queue
      sns:
        order-expiration-topic: arn:aws:sns:us-west-2:000000000000:order-expiration-topic

      dynamodb:
        endpoint: http://localhost:8000

      redis:
        orders-stream: orders

app:
  messaging:
    sqs:
      inventory-queue-url: ${spring.cloud.aws.sqs.inventory-request-queue}
      response-queue-url: ${spring.cloud.aws.sqs.inventory-response-queue}
      message-group-id: inventory
    retry:
      max-attempts: 3
      backoff-millis: 100
    audit:
      enabled: ${ticketing.statemachine.audit-enabled:false}

ticketing:
  cache:
    ttl-minutes: 5
  statemachine:
    audit-enabled: true

logging:
  level:
    root: INFO
    com.nequi: INFO
    org.springframework.statemachine: DEBUG
    org.springframework.data.redis: INFO