aws:
  region: us-east-1
  access-key: dummy
  secret-key: dummy
  dynamodb:
    endpoint: http://localhost:8000
  sqs:
    endpoint: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/orders-queue

ticketing:
  statemachine:
    audit-enabled: true

logging:
  level:
    root: INFO
    com.nequi: INFO
    org.springframework.statemachine: DEBUG
