
ticketing:
  statemachine:
    audit-enabled: true

aws:
  endpoint-override: http://localstack:4566
  region: us-east-1
  access-key: test
  secret-key: test

logging:
  level:
    root: INFO
    com.nequi: INFO
    org.springframework.statemachine: INFO